#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yunohost_diagnosis"
name = "Yunohost Diagnosis"

description.en = "diagnosis.yunohost.org package"
description.fr = "diagnosis.yunohost.org package"

version = "1.0~ynh1"

maintainers = ["salamandar"]

[upstream]
license = "AGPL-3.0"
website = "https://github.com/YunoHost/check-http"
demo = "https://diagnosis.yunohost.org"

code = "https://github.com/YunoHost/check-http"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
