#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

_git_clone_or_pull "$install_dir/check-http"

chown -R $app:www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's configuration file..."

ynh_config_add --template="" --destination="$install_dir/"

chmod 400 "$install_dir/"
chown "$app:$app" "$install_dir/"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

pushd "$install_dir" > /dev/null
_update_venv
popd > /dev/null

pushd "$install_dir/check-http" > /dev/null
{
    ynh_exec_as_app "$install_dir/venv/bin/pip" install -r requirements.txt > /dev/null
    ynh_exec_as_app "$install_dir/venv/bin/pip" install gunicorn > /dev/null
}
popd > /dev/null

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Service for diagnosis.yunohost.org" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting app's systemd service..."

ynh_systemd_action --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
